/**
 * Difference-workbook contract, asserted against the REAL generated bytes —
 * specification sections 25, 34 and 41 (scenario 13).
 *
 * Building the workbook and reading it back catches contract drift that a
 * test against the in-memory model would miss.
 */

import { describe, expect, it } from 'vitest';
import {
  buildDifferenceWorkbook,
  buildFailedRowsWorkbook,
  readWorkbookRows,
} from '../../netlify/shared/excel/workbook';
import { buildExportRows, type ExportableItem } from '../../src/domain/exportContract';

const ITEMS: ExportableItem[] = [
  {
    itemName: 'Hex Bolt M8',
    sku: 'SKU-0001',
    quantityDifference: 0,
    resultStatus: 'matched',
    submittedAt: '2026-07-25T10:00:00Z',
  },
  {
    itemName: 'Hex Nut M8',
    sku: 'SKU-0002',
    quantityDifference: 2,
    resultStatus: 'mismatched',
    submittedAt: '2026-07-25T10:01:00Z',
  },
  {
    itemName: 'Washer M8',
    sku: 'SKU-0003',
    quantityDifference: -3,
    resultStatus: 'mismatched',
    submittedAt: '2026-07-25T10:02:00Z',
  },
  {
    itemName: 'Leading Zero Part',
    sku: '0012345',
    quantityDifference: 1,
    resultStatus: 'mismatched',
    submittedAt: '2026-07-25T10:03:00Z',
  },
];

describe('buildDifferenceWorkbook — column contract', () => {
  it('writes exactly the three required headings, in order, on row 1', async () => {
    const bytes = await buildDifferenceWorkbook(buildExportRows(ITEMS));
    const { headers } = await readWorkbookRows(bytes);

    // No title row above the headings.
    expect(headers).toEqual(['Item Name', 'SKU', 'Qty Difference']);
    expect(headers).toHaveLength(3);
  });

  it('adds no extra columns', async () => {
    const bytes = await buildDifferenceWorkbook(buildExportRows(ITEMS));
    const { rows } = await readWorkbookRows(bytes);
    for (const row of rows) expect(row).toHaveLength(3);
  });

  it('writes the difference as a signed NUMBER, not text', async () => {
    const bytes = await buildDifferenceWorkbook(buildExportRows(ITEMS));
    const { rows } = await readWorkbookRows(bytes);

    expect(rows[0]?.[2]).toBe(0);
    expect(rows[1]?.[2]).toBe(2);
    expect(rows[2]?.[2]).toBe(-3);
    for (const row of rows) expect(typeof row[2]).toBe('number');
  });

  it('preserves SKU leading zeros', async () => {
    const bytes = await buildDifferenceWorkbook(buildExportRows(ITEMS));
    const { rows } = await readWorkbookRows(bytes);

    const leadingZeroRow = rows.find((row) => String(row[0]).includes('Leading Zero'));
    expect(leadingZeroRow?.[1]).toBe('0012345');
  });

  it('produces a real, non-empty xlsx payload', async () => {
    const bytes = await buildDifferenceWorkbook(buildExportRows(ITEMS));
    expect(bytes.byteLength).toBeGreaterThan(1000);
    // ZIP local-file-header magic: PK\x03\x04
    expect(bytes[0]).toBe(0x50);
    expect(bytes[1]).toBe(0x4b);
  });
});

describe('buildDifferenceWorkbook — filters', () => {
  it('keeps the format identical regardless of the filter', async () => {
    const all = await readWorkbookRows(await buildDifferenceWorkbook(buildExportRows(ITEMS, 'all_submitted')));
    const mismatched = await readWorkbookRows(
      await buildDifferenceWorkbook(buildExportRows(ITEMS, 'mismatched_only')),
    );
    const matched = await readWorkbookRows(
      await buildDifferenceWorkbook(buildExportRows(ITEMS, 'matched_only')),
    );

    // Same headings every time; only the row set changes.
    expect(all.headers).toEqual(mismatched.headers);
    expect(all.headers).toEqual(matched.headers);

    expect(all.rows).toHaveLength(4);
    expect(mismatched.rows).toHaveLength(3);
    expect(matched.rows).toHaveLength(1);
  });
});

describe('buildDifferenceWorkbook — formula injection (section 34)', () => {
  it('neutralizes a formula in a text cell while leaving the number alone', async () => {
    const bytes = await buildDifferenceWorkbook([
      { itemName: '=HYPERLINK("http://evil.example","Click")', sku: '-SKU-1', qtyDifference: -5 },
      { itemName: '@SUM(1,1)', sku: '+1234', qtyDifference: 3 },
    ]);
    const { rows } = await readWorkbookRows(bytes);

    // Text cells are prefixed so no spreadsheet evaluates them.
    expect(String(rows[0]?.[0])).toMatch(/^'=/);
    expect(String(rows[0]?.[1])).toMatch(/^'-/);
    expect(String(rows[1]?.[0])).toMatch(/^'@/);
    expect(String(rows[1]?.[1])).toMatch(/^'\+/);

    // The legitimate negative NUMBER is untouched.
    expect(rows[0]?.[2]).toBe(-5);
    expect(rows[1]?.[2]).toBe(3);
  });
});

describe('buildDifferenceWorkbook — empty export', () => {
  it('still emits the header row when nothing has been submitted', async () => {
    const bytes = await buildDifferenceWorkbook([]);
    const { headers, rows } = await readWorkbookRows(bytes);
    expect(headers).toEqual(['Item Name', 'SKU', 'Qty Difference']);
    expect(rows).toHaveLength(0);
  });
});

describe('buildFailedRowsWorkbook (section 17)', () => {
  it('writes the five documented columns', async () => {
    const bytes = await buildFailedRowsWorkbook([
      {
        sourceRow: 3,
        rawValue: 'BAD-SKU',
        normalizedSku: 'BAD-SKU',
        failureCode: 'SKU_NOT_FOUND',
        failureReason: 'No active Zoho Books item was found with this exact SKU.',
      },
    ]);
    const { headers, rows } = await readWorkbookRows(bytes);

    expect(headers).toEqual([
      'Source Row',
      'Raw Value',
      'Normalized SKU',
      'Failure Code',
      'Failure Reason',
    ]);
    expect(rows[0]?.[0]).toBe(3);
    expect(rows[0]?.[3]).toBe('SKU_NOT_FOUND');
  });
});
